import type { SupabaseClient } from '../../db/supabase.client';
import type { NpcProfileLogDTO, OperationType } from '../../types';

export class LogService {
  constructor(private supabase: SupabaseClient) {}

  /**
   * Logs an NPC profile operation
   * @param operation Operation type (INSERT, UPDATE, DELETE, GENERATE, OPEN)
   * @param npcProfileId ID of the NPC profile (optional for GENERATE operations)
   * @param userId ID of the user performing the operation
   * @param duration Operation duration in milliseconds (optional)
   */
  async logOperation(
    operation: OperationType,
    npcProfileId: string | null,
    userId: string,
    duration: number | null = null
  ): Promise<void> {
    try {
      // Create strongly typed log entry, omitting the 'id' field which is generated by the database
      const logEntry: Omit<NpcProfileLogDTO, 'id'> = {
        npc_profile_id: npcProfileId,
        operation,
        operation_timestamp: new Date().toISOString(),
        duration,
        user_id: userId,
        user_role: 'user' // TODO: Get actual user role from auth context
      };

      const { error } = await this.supabase
        .from('npc_profile_logs')
        .insert(logEntry);

      if (error) {
        console.error('Failed to log operation:', error);
      }
    } catch (error) {
      // Log error but don't throw to prevent disrupting the main operation flow
      console.error('Error logging operation:', error);
    }
  }
} 